# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 3m
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
    # skip for now, 'cause it's inherited and has lots of linter problems to fix.
  revive:
    rules:
      - name: line-length-limit
        arguments: 120
  skip-dirs:
    - ".*mocks.*"
    - vendor
    - ".*gen.*"
    - "pb"
  gofumports:
    local-prefixes: "github.com/tomakado/kvevri"

output:
  sort-results: true

issues:
  exclude-use-default: true
  fix: false
  exclude-rules:
    - linters:
        - revive
      text: 'should not use basic type string as key in context.WithValue'

    - linters:
        - revive
      text: "don't use an underscore in package name"

    - linters:
        - staticcheck
      text: 'SA1029:' # the same as revive's rule about string as a key in context.WithValue

    - linters:
        - revive
      text: "comment on exported var"

linters:
  enable:
    - revive
    - gofmt
    - gosimple
    - misspell
    - goimports
    - godot
    - cyclop
    - gocognit
    - gocritic
    - prealloc
    - wsl
    - goconst
